[project]
name = "quark"
version = "0.1"
description = "The Quark source tree package (idk what else to call it)"
requires-python = ">= 3.13"
authors = [
    { name = "Thiruvalluvan Kamaraj", email = "thiruisanidiot@gmail.com" },
]
readme = "docs/README.md"
license = "Apache-2.0"

[tool.setuptools]
packages = ["src"]
